version: '3.7'

services:
  nginx:
    restart: always
    image: nginx:1.17.9-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: reverse-proxy

networks:
  default:
    external:
      name: spine_ext
